module.exports = Object.freeze({
    INVALID_PASSWORD:'INVALID_PASSWORD',
    INVALID_LOGIN_CREDENTIAL:'INVALID_LOGIN_CREDENTIAL',
    TOKEN_NOT_UPDATED: 'TOKEN_NOT_UPDATED',
    INVALID_REFERESH_TOKEN: 'INVALID_REFERESH_TOKEN',
    RECORD_ALREADY_EXISTS: 'RECORD_ALREADY_EXISTS',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    EMPLOYEE_CODE_PREFIX: 'EMP-',
    AMOUNT_REQUIRED: 'AMOUNT_REQUIRED',
    PASSWORD_NOT_MATCHES: 'PASSWORD_NOT_MATCHES',
    CURRENT_PASSWORD_INVALID: 'CURRENT_PASSWORD_INVALID',
});